// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func QuickCaptureModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"quick-capture-modal\" class=\"modal\"><div class=\"modal-box\"><h3 class=\"font-bold text-lg\">Quick Capture</h3><p class=\"py-2\">Quickly capture a new task or idea. It will be added to your inbox for processing later.</p><form method=\"POST\" action=\"/tasks\"><div class=\"form-control\"><label class=\"label\"><span class=\"label-text\">Task/Idea Title</span></label> <input type=\"text\" name=\"title\" placeholder=\"Enter title...\" class=\"input input-bordered\" required></div><div class=\"form-control mt-2\"><label class=\"label\"><span class=\"label-text\">Description (optional)</span></label> <textarea name=\"description\" placeholder=\"Enter description...\" class=\"textarea textarea-bordered\" rows=\"3\"></textarea></div><div class=\"form-control mt-4\"><button type=\"submit\" id=\"quick-capture-submit\" class=\"btn btn-primary\">Capture</button></div></form><div class=\"modal-action\"><form method=\"dialog\"><button class=\"btn\">Close</button></form></div></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
